# Generated by Django 2.1.2 on 2018-10-14 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('honeypot', '0004_auto_20181014_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='message',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
