# Generated by Django 2.1.2 on 2018-10-16 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('honeypot', '0005_contact_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='login',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='password',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
