# Generated by Django 2.1.2 on 2018-10-16 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('honeypot', '0007_auto_20181016_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='sujet',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
